"""Core data types shared across the broker, signals, and engine."""
from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Optional


class Origin(str, Enum):
    """Where the instruction behind an action came from."""
    USER = "user"            # came directly from the human principal
    AGENT = "agent"          # generated by the agent's own reasoning
    UNTRUSTED = "untrusted"  # derived from data the agent read (email, web, a doc)


@dataclass
class ActionRequest:
    """A single action an agent wants to take, evaluated *before* it happens."""
    agent_id: str
    principal: str                              # the human the agent acts for
    task: str                                   # what the agent was actually asked to do
    action: str                                 # the operation, e.g. "wire_transfer"
    secret_ref: str                             # the 1Password secret this action needs
    params: dict[str, Any] = field(default_factory=dict)
    origin: Origin = Origin.AGENT               # origin of the instruction
    untrusted_context: Optional[str] = None     # raw untrusted text behind the action


@dataclass
class SignalResult:
    name: str
    risk: float        # 0.0 (safe) .. 1.0 (risky)
    weight: float
    reason: str


@dataclass
class TrustAssessment:
    score: int                       # 0..100 trust
    band: str                        # policy band name
    signals: list[SignalResult]

    def explain(self) -> str:
        lines = [f"trust score: {self.score}/100  ->  {self.band.upper()}"]
        for s in sorted(self.signals, key=lambda x: x.risk * x.weight, reverse=True):
            lines.append(
                f"  - {s.name:13s} risk={s.risk:.2f} w={s.weight:.2f}  {s.reason}"
            )
        return "\n".join(lines)


class Policy(str, Enum):
    ALLOW = "allow"      # full scoped credential
    NARROW = "narrow"    # reduced scope + short TTL
    APPROVE = "approve"  # human in the loop
    DENY = "deny"        # refused, nothing released


@dataclass
class CredentialHandle:
    """An opaque reference handed back to the caller.

    The raw secret value never lives on this object — it stays inside the broker,
    is used to perform the protected call, and is discarded. The agent only ever
    sees the handle.
    """
    secret_ref: str
    ttl_seconds: int
    issued_for: str            # the action this credential was scoped to

    def __repr__(self) -> str:
        return (
            f"CredentialHandle(secret_ref={self.secret_ref!r}, "
            f"ttl={self.ttl_seconds}s, scope={self.issued_for!r})"
        )


@dataclass
class Decision:
    request: ActionRequest
    assessment: TrustAssessment
    policy: Policy
    credential: Optional[CredentialHandle] = None
    reason: str = ""
