from __future__ import annotations

import re
from typing import Sequence

from trustgate.models import ActionRequest, Origin, SignalResult

# Cheap, legible heuristics for prompt-injection in untrusted context.
# This is the hero signal: acting on untrusted-origin instructions should hurt.
INJECTION_PATTERNS = [
    r"ignore (all|previous|the above)",
    r"disregard",
    r"\b(wire|transfer|send|pay)\b.*\b(funds|money|balance|account|\$)",
    r"\bexport\b.*\b(all|table|records|customers?|pii)\b",
    r"\b(delete|drop|wipe)\b",
    r"forward .* to",
]


class ProvenanceSignal:
    """How much do we trust the *origin* of the instruction behind this action?"""
    name = "provenance"

    def __init__(self, weight: float = 0.4):
        self.weight = weight

    def evaluate(
        self, request: ActionRequest, history: Sequence[ActionRequest]
    ) -> SignalResult:
        if request.origin == Origin.UNTRUSTED:
            risk, reason = 0.9, "action derives from untrusted data the agent read"
        elif request.origin == Origin.USER:
            risk, reason = 0.0, "instruction came directly from the principal"
        else:
            risk, reason = 0.3, "action generated by the agent's own reasoning"

        ctx = (request.untrusted_context or "").lower()
        for pat in INJECTION_PATTERNS:
            if re.search(pat, ctx):
                risk = max(risk, 0.85)
                reason = f"injection pattern in untrusted context: /{pat}/"
                break

        return SignalResult(self.name, risk, self.weight, reason)
